<?php

declare(strict_types=1);

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Requests\StoreProductRequest;
use App\Http\Requests\UpdateProductRequest;
use App\Http\Resources\ProductResource;
use App\Models\Product;
use Illuminate\Http\Resources\Json\AnonymousResourceCollection;

/**
 * API ProductController
 * Generated by ModelSchema Enterprise Fragment Architecture
 */
class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(): AnonymousResourceCollection
    {
        $models = Product::paginate();

        return ProductResource::collection($models);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreProductRequest $request): ProductResource
    {
        $model = Product::create($request->validated());

        return new ProductResource($model);
    }

    /**
     * Display the specified resource.
     */
    public function show(Product $model): ProductResource
    {
        return new ProductResource($model);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateProductRequest $request, Product $model): ProductResource
    {
        $model->update($request->validated());

        return new ProductResource($model);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Product $model): \Illuminate\Http\Response
    {
        $model->delete();

        return response()->noContent();
    }
}
