<?php

declare(strict_types=1);

namespace App\Http\Controllers;

use App\Http\Requests\StoreProductRequest;
use App\Http\Requests\UpdateProductRequest;
use App\Models\Product;
use Illuminate\Http\RedirectResponse;
use Illuminate\View\View;

/**
 * Web ProductController
 * Generated by ModelSchema Enterprise Fragment Architecture
 */
class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(): View
    {
        $models = Product::paginate();

        return view('product.index', compact('models'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create(): View
    {
        return view('product.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreProductRequest $request): RedirectResponse
    {
        $model = Product::create($request->validated());

        return redirect()->route('products.show', $model);
    }

    /**
     * Display the specified resource.
     */
    public function show(Product $model): View
    {
        return view('product.show', compact('model'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Product $model): View
    {
        return view('product.edit', compact('model'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateProductRequest $request, Product $model): RedirectResponse
    {
        $model->update($request->validated());

        return redirect()->route('products.show', $model);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Product $model): RedirectResponse
    {
        $model->delete();

        return redirect()->route('products.index');
    }
}
